# all durations in seconds!

# MIN_DURATION_FOR_FAMILY = 32
MIN_DURATION_FOR_FAMILY = 51
# MAX_DURATION_FOR_FAMILY = 7.1 * 60
MAX_DURATION_FOR_FAMILY = 7.85 * 60

# MIN_DURATION_FOR_REST = 31
MIN_DURATION_FOR_REST = 13.5
# MAX_DURATION_FOR_REST = 3.2 * 60
MAX_DURATION_FOR_REST = 1.15 * 60

# MIN_DURATION_FOR_ROOT = 10
MIN_DURATION_FOR_ROOT = 12
# MAX_DURATION_FOR_ROOT = 36
MAX_DURATION_FOR_ROOT = 35

MIN_MOVEMENT_SPAN = 1
MAX_MOVEMENT_SPAN = 7
