COMPUTE_FAMILIES_PITCH = False
COMPUTE_STOCHASTIC_PARTS = False
COMPUTE_BELLS = False
COMPUTE_SATURATION_TONES = False

RENDER_SOUNDFILES = False
RENDER_MIDIFILES = False
RENDER_NOTATION = False
RENDER_VIDEOS = True
