ID_RADIO_VIOLIN = "radioViolin"
ID_RADIO_SAXOPHONE = "radioSaxophone"
ID_RADIO_BOAT0 = "radioBoat0"
ID_RADIO_BOAT1 = "radioBoat1"
ID_RADIO_BOAT2 = "radioBoat2"

LOUDSPEAKERS = (ID_RADIO_VIOLIN, ID_RADIO_SAXOPHONE, ID_RADIO_BOAT0, ID_RADIO_BOAT1, ID_RADIO_BOAT2)
